server:
  port: 8080

spring:
  application:
    name: bank-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-thers: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
